from . import patient
from . import doctor
from . import appointment
from . import prescription
from . import consultation
from . import billing
from . import sales_integration
from . import accounting_integration
from . import multi_company